// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Tasarim.Data;

#nullable disable

namespace Tasarim.Data.Migrations
{
    [DbContext(typeof(DatabaseContext))]
    [Migration("20260428165130_SepetTablolariDuzenlendi")]
    partial class SepetTablolariDuzenlendi
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Tasarim.Core.Entities.Favori", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<int>("KullaniciID")
                        .HasColumnType("int");

                    b.Property<int>("UrunID")
                        .HasColumnType("int");

                    b.HasKey("ID");

                    b.HasIndex("KullaniciID");

                    b.HasIndex("UrunID");

                    b.ToTable("Favoriler");
                });

            modelBuilder.Entity("Tasarim.Core.Entities.Kampanya", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<string>("Aciklama")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("varchar(250)");

                    b.Property<int>("IndirimTipi")
                        .HasColumnType("int");

                    b.Property<decimal>("IndirimTutari")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("KampanyaAd")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<bool>("KampanyaAktifMi")
                        .HasColumnType("bit");

                    b.Property<string>("KampanyaResmi")
                        .HasMaxLength(150)
                        .HasColumnType("varchar(150)");

                    b.HasKey("ID");

                    b.ToTable("Kampanyalar");
                });

            modelBuilder.Entity("Tasarim.Core.Entities.KampanyaUrunleri", b =>
                {
                    b.Property<int>("UrunID")
                        .HasColumnType("int");

                    b.Property<int>("KampanyaID")
                        .HasColumnType("int");

                    b.HasKey("UrunID", "KampanyaID");

                    b.HasIndex("KampanyaID");

                    b.ToTable("KampanyaUrunleri");
                });

            modelBuilder.Entity("Tasarim.Core.Entities.Kategori", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<bool>("AktifMi")
                        .HasColumnType("bit");

                    b.Property<string>("KategoriAd")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<string>("KategoriResmi")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("SiraNo")
                        .HasColumnType("int");

                    b.Property<int?>("UstKategoriID")
                        .HasColumnType("int");

                    b.Property<bool>("UstteGoster")
                        .HasColumnType("bit");

                    b.HasKey("ID");

                    b.HasIndex("UstKategoriID");

                    b.ToTable("Kategoriler");

                    b.HasData(
                        new
                        {
                            ID = 1,
                            AktifMi = true,
                            KategoriAd = "Erkek",
                            SiraNo = 1,
                            UstteGoster = true
                        },
                        new
                        {
                            ID = 2,
                            AktifMi = true,
                            KategoriAd = "Kadin",
                            SiraNo = 2,
                            UstteGoster = true
                        },
                        new
                        {
                            ID = 3,
                            AktifMi = true,
                            KategoriAd = "Elektronik",
                            SiraNo = 3,
                            UstteGoster = false
                        });
                });

            modelBuilder.Entity("Tasarim.Core.Entities.Kullanici", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<bool>("AdminMi")
                        .HasColumnType("bit");

                    b.Property<string>("KullaniciAd")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("varchar(30)");

                    b.Property<string>("Sifre")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("varchar(64)");

                    b.HasKey("ID");

                    b.ToTable("Kullanicilar");

                    b.HasData(
                        new
                        {
                            ID = 1,
                            AdminMi = true,
                            KullaniciAd = "Admin",
                            Sifre = "1"
                        },
                        new
                        {
                            ID = 2,
                            AdminMi = false,
                            KullaniciAd = "Kullanıcı",
                            Sifre = "1"
                        });
                });

            modelBuilder.Entity("Tasarim.Core.Entities.LLSonuc", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<string>("DuyguDagilim")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("SonGuncelleme")
                        .HasColumnType("datetime2");

                    b.Property<string>("TopArtilar")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TopEksiler")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("ToplamYorum")
                        .HasColumnType("int");

                    b.Property<int>("UrunID")
                        .HasColumnType("int");

                    b.HasKey("ID");

                    b.HasIndex("UrunID")
                        .IsUnique();

                    b.ToTable("LLSonuclari");
                });

            modelBuilder.Entity("Tasarim.Core.Entities.Marka", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<bool>("AktifMi")
                        .HasColumnType("bit");

                    b.Property<string>("Logo")
                        .HasMaxLength(150)
                        .HasColumnType("varchar(150)");

                    b.Property<string>("MarkaAd")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.HasKey("ID");

                    b.ToTable("Markalar");

                    b.HasData(
                        new
                        {
                            ID = 1,
                            AktifMi = true,
                            MarkaAd = "Beyoğlu Abiye"
                        },
                        new
                        {
                            ID = 2,
                            AktifMi = true,
                            MarkaAd = "Tuay"
                        },
                        new
                        {
                            ID = 3,
                            AktifMi = true,
                            MarkaAd = "Hennin"
                        });
                });

            modelBuilder.Entity("Tasarim.Core.Entities.Odeme", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<string>("IslemNo")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<string>("OdemeDurumu")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)");

                    b.Property<DateTime>("OdemeTarihi")
                        .HasColumnType("datetime2");

                    b.Property<int>("SiparisID")
                        .HasColumnType("int");

                    b.Property<decimal>("Tutar")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("ID");

                    b.HasIndex("SiparisID");

                    b.ToTable("Odemeler");
                });

            modelBuilder.Entity("Tasarim.Core.Entities.Profil", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<string>("Ad")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("varchar(30)");

                    b.Property<string>("Adres")
                        .HasMaxLength(250)
                        .HasColumnType("varchar(250)");

                    b.Property<double?>("Boy")
                        .HasColumnType("float");

                    b.Property<string>("Cinsiyet")
                        .HasMaxLength(5)
                        .HasColumnType("varchar(5)");

                    b.Property<double?>("Kilo")
                        .HasColumnType("float");

                    b.Property<int>("KullaniciID")
                        .HasColumnType("int");

                    b.Property<string>("Mail")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<string>("Soyad")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("varchar(30)");

                    b.Property<string>("TelNo")
                        .HasMaxLength(15)
                        .HasColumnType("varchar(15)");

                    b.Property<int?>("Yas")
                        .HasColumnType("int");

                    b.HasKey("ID");

                    b.HasIndex("KullaniciID")
                        .IsUnique();

                    b.ToTable("Profiller");

                    b.HasData(
                        new
                        {
                            ID = 1,
                            Ad = "Admin",
                            Adres = "Üsküdar",
                            KullaniciID = 1,
                            Mail = "info@admin.com",
                            Soyad = "1"
                        },
                        new
                        {
                            ID = 2,
                            Ad = "Kullanıcı",
                            Adres = "Ümraniye",
                            KullaniciID = 2,
                            Mail = "info@kullanıcı.com",
                            Soyad = "1"
                        });
                });

            modelBuilder.Entity("Tasarim.Core.Entities.Resim", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<string>("ResimYolu")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)");

                    b.Property<int?>("SiraNo")
                        .HasColumnType("int");

                    b.Property<int?>("UrunID")
                        .HasColumnType("int");

                    b.HasKey("ID");

                    b.HasIndex("UrunID");

                    b.ToTable("Resimler");
                });

            modelBuilder.Entity("Tasarim.Core.Entities.Sepet", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<int>("KullaniciID")
                        .HasColumnType("int");

                    b.HasKey("ID");

                    b.HasIndex("KullaniciID")
                        .IsUnique();

                    b.ToTable("Sepetler");
                });

            modelBuilder.Entity("Tasarim.Core.Entities.SepetItem", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<int>("Adet")
                        .HasColumnType("int");

                    b.Property<int>("SepetID")
                        .HasColumnType("int");

                    b.Property<int?>("UrunID")
                        .HasColumnType("int");

                    b.Property<int>("UrunVaryasyonID")
                        .HasColumnType("int");

                    b.HasKey("ID");

                    b.HasIndex("SepetID");

                    b.HasIndex("UrunID");

                    b.HasIndex("UrunVaryasyonID");

                    b.ToTable("SepetItems");
                });

            modelBuilder.Entity("Tasarim.Core.Entities.Siparis", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<string>("KargoNo")
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)");

                    b.Property<int>("KullaniciID")
                        .HasColumnType("int");

                    b.Property<int>("SiparisDurumuID")
                        .HasColumnType("int");

                    b.Property<string>("SiparisNo")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)");

                    b.Property<DateTime>("SiparisTarihi")
                        .HasColumnType("datetime2");

                    b.Property<decimal>("ToplamTutar")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("ID");

                    b.HasIndex("KullaniciID");

                    b.HasIndex("SiparisDurumuID");

                    b.ToTable("Siparisler");
                });

            modelBuilder.Entity("Tasarim.Core.Entities.SiparisDetay", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<int>("Adet")
                        .HasColumnType("int");

                    b.Property<decimal>("BirimFiyat")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("SiparisID")
                        .HasColumnType("int");

                    b.Property<int>("UrunID")
                        .HasColumnType("int");

                    b.HasKey("ID");

                    b.HasIndex("SiparisID");

                    b.HasIndex("UrunID");

                    b.ToTable("SiparisDetaylari");
                });

            modelBuilder.Entity("Tasarim.Core.Entities.SiparisDurumu", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<string>("DurumAd")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("varchar(30)");

                    b.HasKey("ID");

                    b.ToTable("SiparisDurumlari");

                    b.HasData(
                        new
                        {
                            ID = 1,
                            DurumAd = "Onay Bekliyor"
                        },
                        new
                        {
                            ID = 2,
                            DurumAd = "Hazırlanıyor"
                        },
                        new
                        {
                            ID = 3,
                            DurumAd = "Kargolandı"
                        },
                        new
                        {
                            ID = 4,
                            DurumAd = "Teslim Edildi"
                        });
                });

            modelBuilder.Entity("Tasarim.Core.Entities.Slider", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<string>("Baslik")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<string>("Link")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)");

                    b.Property<int>("SiraNo")
                        .HasColumnType("int");

                    b.Property<string>("SliderAciklama")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("varchar(250)");

                    b.Property<string>("SliderResim")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("varchar(150)");

                    b.HasKey("ID");

                    b.ToTable("Sliders");
                });

            modelBuilder.Entity("Tasarim.Core.Entities.Urun", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<string>("Aciklama")
                        .HasMaxLength(1000)
                        .HasColumnType("varchar(1000)");

                    b.Property<bool>("AktifMi")
                        .HasColumnType("bit");

                    b.Property<string>("AnaResim")
                        .HasMaxLength(150)
                        .HasColumnType("varchar(150)");

                    b.Property<string>("Baslik")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<decimal>("Fiyat")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("KategoriID")
                        .HasColumnType("int");

                    b.Property<int>("MarkaID")
                        .HasColumnType("int");

                    b.Property<string>("ModelKodu")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Renk")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UrunKod")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)");

                    b.HasKey("ID");

                    b.HasIndex("KategoriID");

                    b.HasIndex("MarkaID");

                    b.ToTable("Urunler");
                });

            modelBuilder.Entity("Tasarim.Core.Entities.UrunVaryasyon", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<string>("Beden")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("StokAdedi")
                        .HasColumnType("int");

                    b.Property<int>("UrunID")
                        .HasColumnType("int");

                    b.HasKey("ID");

                    b.HasIndex("UrunID");

                    b.ToTable("UrunVaryasyonlari");
                });

            modelBuilder.Entity("Tasarim.Core.Entities.Yorum", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<int?>("KullaniciID")
                        .HasColumnType("int");

                    b.Property<int>("ProfilID")
                        .HasColumnType("int");

                    b.Property<int>("Puan")
                        .HasColumnType("int");

                    b.Property<DateTime>("Tarih")
                        .HasColumnType("datetime2");

                    b.Property<int>("UrunID")
                        .HasColumnType("int");

                    b.Property<string>("YorumIcerik")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ID");

                    b.HasIndex("KullaniciID");

                    b.HasIndex("ProfilID");

                    b.HasIndex("UrunID");

                    b.ToTable("Yorumlar");
                });

            modelBuilder.Entity("Tasarim.Core.Entities.YorumAnaliz", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<string>("Artilar")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Duygu")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Eksiler")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Oneriler")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Sikayetler")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("YorumID")
                        .HasColumnType("int");

                    b.HasKey("ID");

                    b.HasIndex("YorumID")
                        .IsUnique();

                    b.ToTable("YorumAnalizleri");
                });

            modelBuilder.Entity("Tasarim.Core.Entities.İletisim", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("AdSoyad")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Konu")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Mesaj")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("MesajTarihi")
                        .HasColumnType("datetime2");

                    b.Property<bool>("OkunduMu")
                        .HasColumnType("bit");

                    b.HasKey("Id");

                    b.ToTable("İletisimler");
                });

            modelBuilder.Entity("Tasarim.Core.Entities.Favori", b =>
                {
                    b.HasOne("Tasarim.Core.Entities.Kullanici", "Kullanici")
                        .WithMany("Favoriler")
                        .HasForeignKey("KullaniciID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Tasarim.Core.Entities.Urun", "Urun")
                        .WithMany("Favoriler")
                        .HasForeignKey("UrunID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Kullanici");

                    b.Navigation("Urun");
                });

            modelBuilder.Entity("Tasarim.Core.Entities.KampanyaUrunleri", b =>
                {
                    b.HasOne("Tasarim.Core.Entities.Kampanya", "Kampanya")
                        .WithMany("KampanyaUrunleri")
                        .HasForeignKey("KampanyaID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Tasarim.Core.Entities.Urun", "Urun")
                        .WithMany("KampanyaUrunleri")
                        .HasForeignKey("UrunID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Kampanya");

                    b.Navigation("Urun");
                });

            modelBuilder.Entity("Tasarim.Core.Entities.Kategori", b =>
                {
                    b.HasOne("Tasarim.Core.Entities.Kategori", "UstKategori")
                        .WithMany()
                        .HasForeignKey("UstKategoriID");

                    b.Navigation("UstKategori");
                });

            modelBuilder.Entity("Tasarim.Core.Entities.LLSonuc", b =>
                {
                    b.HasOne("Tasarim.Core.Entities.Urun", "Urun")
                        .WithOne("LLSonuc")
                        .HasForeignKey("Tasarim.Core.Entities.LLSonuc", "UrunID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Urun");
                });

            modelBuilder.Entity("Tasarim.Core.Entities.Odeme", b =>
                {
                    b.HasOne("Tasarim.Core.Entities.Siparis", "Siparis")
                        .WithMany("Odemeler")
                        .HasForeignKey("SiparisID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Siparis");
                });

            modelBuilder.Entity("Tasarim.Core.Entities.Profil", b =>
                {
                    b.HasOne("Tasarim.Core.Entities.Kullanici", "Kullanici")
                        .WithOne("Profil")
                        .HasForeignKey("Tasarim.Core.Entities.Profil", "KullaniciID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Kullanici");
                });

            modelBuilder.Entity("Tasarim.Core.Entities.Resim", b =>
                {
                    b.HasOne("Tasarim.Core.Entities.Urun", "Urun")
                        .WithMany("Resimler")
                        .HasForeignKey("UrunID");

                    b.Navigation("Urun");
                });

            modelBuilder.Entity("Tasarim.Core.Entities.Sepet", b =>
                {
                    b.HasOne("Tasarim.Core.Entities.Kullanici", "Kullanici")
                        .WithOne("Sepet")
                        .HasForeignKey("Tasarim.Core.Entities.Sepet", "KullaniciID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Kullanici");
                });

            modelBuilder.Entity("Tasarim.Core.Entities.SepetItem", b =>
                {
                    b.HasOne("Tasarim.Core.Entities.Sepet", "Sepet")
                        .WithMany("SepetItems")
                        .HasForeignKey("SepetID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Tasarim.Core.Entities.Urun", null)
                        .WithMany("SepetItems")
                        .HasForeignKey("UrunID");

                    b.HasOne("Tasarim.Core.Entities.UrunVaryasyon", "UrunVaryasyon")
                        .WithMany()
                        .HasForeignKey("UrunVaryasyonID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Sepet");

                    b.Navigation("UrunVaryasyon");
                });

            modelBuilder.Entity("Tasarim.Core.Entities.Siparis", b =>
                {
                    b.HasOne("Tasarim.Core.Entities.Kullanici", "Kullanici")
                        .WithMany("Siparisler")
                        .HasForeignKey("KullaniciID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Tasarim.Core.Entities.SiparisDurumu", "SiparisDurumu")
                        .WithMany("Siparisler")
                        .HasForeignKey("SiparisDurumuID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Kullanici");

                    b.Navigation("SiparisDurumu");
                });

            modelBuilder.Entity("Tasarim.Core.Entities.SiparisDetay", b =>
                {
                    b.HasOne("Tasarim.Core.Entities.Siparis", "Siparis")
                        .WithMany("SiparisDetaylari")
                        .HasForeignKey("SiparisID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Tasarim.Core.Entities.Urun", "Urun")
                        .WithMany("SiparisDetaylari")
                        .HasForeignKey("UrunID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Siparis");

                    b.Navigation("Urun");
                });

            modelBuilder.Entity("Tasarim.Core.Entities.Urun", b =>
                {
                    b.HasOne("Tasarim.Core.Entities.Kategori", "Kategori")
                        .WithMany("Urunler")
                        .HasForeignKey("KategoriID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Tasarim.Core.Entities.Marka", "Marka")
                        .WithMany("Urunler")
                        .HasForeignKey("MarkaID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Kategori");

                    b.Navigation("Marka");
                });

            modelBuilder.Entity("Tasarim.Core.Entities.UrunVaryasyon", b =>
                {
                    b.HasOne("Tasarim.Core.Entities.Urun", "Urun")
                        .WithMany("Varyasyonlar")
                        .HasForeignKey("UrunID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Urun");
                });

            modelBuilder.Entity("Tasarim.Core.Entities.Yorum", b =>
                {
                    b.HasOne("Tasarim.Core.Entities.Kullanici", null)
                        .WithMany("Yorumlar")
                        .HasForeignKey("KullaniciID");

                    b.HasOne("Tasarim.Core.Entities.Profil", "Profil")
                        .WithMany()
                        .HasForeignKey("ProfilID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Tasarim.Core.Entities.Urun", "Urun")
                        .WithMany("Yorumlar")
                        .HasForeignKey("UrunID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Profil");

                    b.Navigation("Urun");
                });

            modelBuilder.Entity("Tasarim.Core.Entities.YorumAnaliz", b =>
                {
                    b.HasOne("Tasarim.Core.Entities.Yorum", "Yorum")
                        .WithOne("YorumAnaliz")
                        .HasForeignKey("Tasarim.Core.Entities.YorumAnaliz", "YorumID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Yorum");
                });

            modelBuilder.Entity("Tasarim.Core.Entities.Kampanya", b =>
                {
                    b.Navigation("KampanyaUrunleri");
                });

            modelBuilder.Entity("Tasarim.Core.Entities.Kategori", b =>
                {
                    b.Navigation("Urunler");
                });

            modelBuilder.Entity("Tasarim.Core.Entities.Kullanici", b =>
                {
                    b.Navigation("Favoriler");

                    b.Navigation("Profil");

                    b.Navigation("Sepet");

                    b.Navigation("Siparisler");

                    b.Navigation("Yorumlar");
                });

            modelBuilder.Entity("Tasarim.Core.Entities.Marka", b =>
                {
                    b.Navigation("Urunler");
                });

            modelBuilder.Entity("Tasarim.Core.Entities.Sepet", b =>
                {
                    b.Navigation("SepetItems");
                });

            modelBuilder.Entity("Tasarim.Core.Entities.Siparis", b =>
                {
                    b.Navigation("Odemeler");

                    b.Navigation("SiparisDetaylari");
                });

            modelBuilder.Entity("Tasarim.Core.Entities.SiparisDurumu", b =>
                {
                    b.Navigation("Siparisler");
                });

            modelBuilder.Entity("Tasarim.Core.Entities.Urun", b =>
                {
                    b.Navigation("Favoriler");

                    b.Navigation("KampanyaUrunleri");

                    b.Navigation("LLSonuc")
                        .IsRequired();

                    b.Navigation("Resimler");

                    b.Navigation("SepetItems");

                    b.Navigation("SiparisDetaylari");

                    b.Navigation("Varyasyonlar");

                    b.Navigation("Yorumlar");
                });

            modelBuilder.Entity("Tasarim.Core.Entities.Yorum", b =>
                {
                    b.Navigation("YorumAnaliz");
                });
#pragma warning restore 612, 618
        }
    }
}
